### ISSUE TITLE
It deletes messages older than 7 days, unless running FULL_SYNC

### ISSUE THREAD

**Issue by noreklint** [innosat-mats/L0-fetcher#12]
# 🐛 Description

Ipsum lorem..

# 🔢 To reproduce

# ✌🏽 Expected behaviour

What should have happened

# 📷 Screenshots

If applicable

# 💻 Traceback

```
Paste logs here...
```

**Comment by skymandr** [comment]
We will use full sync, but it doesn't require an issue.
